# Generated by Django 6.0.7 on 2026-08-11 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_service_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staffmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], db_index=True, default='STAFF', max_length=10),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic'], name='clinics_app_clinic__500681_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'appointment_datetime'], name='clinics_app_clinic__ecf96e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='clinics_app_clinic__6cf122_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['clinic'], name='clinics_cli_clinic__c7b1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['clinic', 'first_name'], name='clinics_cli_clinic__04cd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['clinic', 'last_name'], name='clinics_cli_clinic__e8063a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['clinic', 'phone'], name='clinics_cli_clinic__efd2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic'], name='clinics_ser_clinic__c0a25a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic', 'name'], name='clinics_ser_clinic__6f70f2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmembership',
            index=models.Index(fields=['clinic'], name='clinics_sta_clinic__93fd26_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmembership',
            index=models.Index(fields=['clinic', 'user'], name='clinics_sta_clinic__8d6049_idx'),
        ),
    ]
