# Generated by Django 6.0.7 on 2026-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resend_count', models.IntegerField(default=0)),
                ('last_resend_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'purpose'), name='unique_email_purpose')],
            },
        ),
    ]
