# Generated by Django 6.0.7 on 2026-07-25 11:11

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
    ]
